version: "3.9"
services:
  zookeeper:
    container_name: sparks-zookeeper
    image: "bitnami/zookeeper:latest"
    ports:
      - ${ZOOKEEPER_PORT}:2181
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=${ZOOKEEPER_USERS}
      - ZOO_SERVER_PASSWORDS=${ZOOKEEPER_USERS_PASSWORDS}
      - ZOO_CLIENT_USER=${ZOOKEEPER_DEFAULT_USER}
      - ZOO_CLIENT_PASSWORD=${ZOOKEEPER_DEFAULT_USER_PASSWORD}
    networks:
      - kafka-network
    volumes:
      - zookeeper-data:/bitnami/zookeeper
  kafka:
    container_name: sparks-kafka
    image: "bitnami/kafka:latest"
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_PROTOCOL=SASL
      - KAFKA_ZOOKEEPER_USER=${KAFKA_ZOOKEEPER_USER}
      - KAFKA_ZOOKEEPER_PASSWORD=${KAFKA_ZOOKEEPER_PASSWORD}
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    volumes:
      - kafka-data:/bitnami/kafka
networks:
  kafka-network:
    name: sparks-kafka-network
    external: true
volumes:
  zookeeper-data:
    name: sparks-zookeeper-data
    external: true
  kafka-data:
    name: sparks-kafka-data
    external: true
