version: "3.9"
services:
  postgres:
    container_name: sparks-postgres
    image: postgres:alpine
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks: 
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
networks:
  postgres-network:
    name: sparks-postgres-network
    driver: bridge
volumes:
  postgres-data:
    name: sparks-postgres-data
